name: lin_player
description: A cross-platform media player built with Flutter.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  lin_player_core:
    path: packages/lin_player_core
  lin_player_server_api:
    path: packages/lin_player_server_api
  lin_player_server_adapters:
    path: packages/lin_player_server_adapters
  lin_player_prefs:
    path: packages/lin_player_prefs
  lin_player_ui:
    path: packages/lin_player_ui
  lin_player_player:
    path: packages/lin_player_player
  lin_player_state:
    path: packages/lin_player_state
  
  file_picker: ^8.0.0+1
  http: ^1.2.2
  crypto: ^3.0.3
  cryptography: ^2.7.0
  xml: ^6.5.0
  shared_preferences: ^2.2.3
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  http_parser: ^4.0.2
  media_kit: ^1.1.11
  media_kit_video: ^1.1.11
  media_kit_libs_android_video: ^1.0.11
  media_kit_libs_ios_video: ^1.0.11
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_linux: ^1.0.11
  media_kit_libs_macos_video: ^1.0.11
  url_launcher: ^6.3.0
  package_info_plus: ^9.0.0
  dynamic_color: ^1.7.0
  flutter_displaymode: ^0.7.0
  video_player: ^2.8.2
  video_player_android: ^2.9.1
  video_player_platform_interface: ^6.6.0
  open_filex: ^4.7.0
  path_provider: ^2.1.2
  qr_flutter: ^4.1.0
  webview_flutter: ^4.4.2
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  media_kit:
    path: packages/media_kit_patched
  video_player_android:
    path: packages/video_player_android_patched

flutter_launcher_icons:
  image_path: assets/app_icon.jpg
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: assets/app_icon.jpg
    icon_size: 256
  macos:
    generate: true
    image_path: assets/app_icon.jpg

flutter:
  uses-material-design: true
  assets:
    - assets/shaders/anime4k/
    - assets/tv_proxy/
    - assets/tv_proxy/mihomo/android/arm64-v8a/
    - assets/tv_proxy/mihomo/android/armeabi-v7a/
    - assets/tv_proxy/mihomo/android/x86_64/
    - assets/tv_proxy/mihomo/android/x86/
    - assets/tv_proxy/metacubexd/
    - assets/tv_remote/
    - assets/tv_remote/images/
