name: lin_player
description: A cross-platform media player built with Flutter.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  file_picker: ^8.0.0+1
  http: ^1.2.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.4.1
  http_parser: ^4.0.2
  media_kit: ^1.1.11
  media_kit_video: ^1.1.11
  media_kit_libs_android_video: ^1.0.11
  media_kit_libs_windows_video: ^1.0.11
  media_kit_libs_linux: ^1.0.11
  media_kit_libs_macos_video: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  media_kit:
    path: packages/media_kit_patched

flutter:
  uses-material-design: true
